### ISSUE TITLE
specific id fields return 200 even if they don't exist

### ISSUE THREAD

**Issue by lucasreed** [heimdal-rw/chmgt#14]
I would expect the second api call to return 404. Same issue with the user api.

```
$ curl localhost:8080/api/changes -i
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 17 Jan 2018 01:57:38 GMT
Content-Length: 3

[]
$ curl localhost:8080/api/changes/1 -i
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 17 Jan 2018 01:57:47 GMT
Content-Length: 113

[{"id":0,"title":"","authorId":0,"requesterId":0,"description":"","reason":"","risk":"","steps":"","revert":""}]
```

If you navigate to an entire top-level endpoint that doesn't exist, it returns as expected:
```
$  curl localhost:8080/api/nonexistent -i
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 17 Jan 2018 02:00:47 GMT
Content-Length: 19

404 page not found
```

**Comment by mattjw79** [comment]
Good catch, #15 should fix the immediate issue. However, it got me thinking about if there are no users or no changes in the database, should a 404 be returned for /api/users or /api/changes? I'm thinking it still should be an empty array like it is now but wanted your input.

**Comment by lucasreed** [comment]
I agree that `/api/users` and `/api/changes` should still return empty arrays. Closing this as it looks like it's fixed to me.
