### ISSUE TITLE
Non-existent item results in 500 error, would expect 404

### ISSUE THREAD

**Issue by lucasreed** [heimdal-rw/chmgt#39]
When calling either a user or changeRequest that does not exist, the API returns a 500 error and logs:
`invalid object id`

I came across this while writing tests that look for a non-existing user.

I fixed it with this diff to the handling/apiUsers.go file. I'll open a PR for this, but leaving the code here so you can comment on if it's the best way to do this @mattjw79 :
```golang
diff --git a/handling/apiUsers.go b/handling/apiUsers.go
index 16d9554..328a259 100644
--- a/handling/apiUsers.go
+++ b/handling/apiUsers.go
@@ -18,6 +18,10 @@ func (h *Handler) GetUsersHandler(w http.ResponseWriter, r *http.Request) {
        var err error
        users, err := h.Datasource.GetUsers(vars["id"])
        if err != nil {
+               if err.Error() == "invalid object id" {
+                       APIWriteFailure(w, "no user found", http.StatusNotFound)
+                       return
+               }
                if vars["id"] == "" || err == models.ErrNoRows {
                        APIWriteFailure(w, "no user found", http.StatusNotFound)
                        return
```

**Comment by lucasreed** [comment]
Also curious if the block just below my additions will ever get matched if they don't get matched when calling a non-existent item.
```golang
if vars["id"] == "" || err == models.ErrNoRows {
     APIWriteFailure(w, "no user found", http.StatusNotFound)
     return
}
```

**Comment by mattjw79** [comment]
What is the request you're using to cause the 500 error? If it's not a valid HexId then the 500 error is appropriate (or possibly a 400 error would be better). Mongo ObjectID: https://docs.mongodb.com/manual/reference/method/ObjectId/

The "invalid object id" is generated at line 112 of models/datasource.go, and perhaps it should be generated like the ErrNoRows (and similarly, checked as such) but with a different name. Maybe:

Line 14ish: `new ErrObjId = errors.New("datasource: invalid object id")`
Line 112ish: `return nil, ErrObjId`

Then it could be checked in the API handler as `err == models.ErrObjId` and return a 400 (now thinking 400 is the better return code).

**Comment by lucasreed** [comment]
I was not using a hexid, that's true.
I was sending something like:
`GET /api/users/0`
I understand what you mean now so I'll rethink it and test using non-existent hexid's.

But now that we're talking about it, why are we using the hexid for the api anyway. Wouldn't it be easier to use the username, which is also unique? I'm thinking of the future when we get more into frontend where people will authenticate with their username and then we'll have to make two different calls to get their information if we use hexid (GET to `/api/users` in order to find the hexid, and then another GET to `/api/users/<hexid>`). If we just map their username to `/api/users/<username>` call we can do it in one request.

Just a thought. Let me know what you think!

EDIT: I'm wrong about using 2 different calls. But it still seems heavy to need to search through `/api/users` for a username instead of just calling `/api/users/<username>`

**Comment by mattjw79** [comment]
Authentication doesn't happen against `/api/users/<id>`, it happens against `/api/authenticate`. The AuthenticateHandler takes in the username and password and queries the database using those items. I think we should keep the users API using the ObjectID because it is idempotent and we may want to allow the username changes.

**Comment by lucasreed** [comment]
Good point! I'll close out that PR as unnecessary. Thanks for clarifying!!
