### ISSUE TITLE
Reading in a config file

### ISSUE THREAD

**Issue by mattjw79** [heimdal-rw/chmgt#4]
If the config file isn't specified on the command line, should it search for one using the following logic:

Look for
1. ./config
2. ~/.chmgt/config
3. /etc/chmgt/config

And the first one that it finds is the one it uses?

**Comment by lucasreed** [comment]
I like this idea. I’ll work on it!

**Comment by lucasreed** [comment]
I've got a working solution. May need to clean up the code though. Example output:
```bash
2018/01/06 21:45:53 Attempting to use config file: ./config
2018/01/06 21:45:53 Config file not found.
2018/01/06 21:45:53 Attempting to use config file: /home/luke/.chmgt/config
2018/01/06 21:45:53 Config file not found.
2018/01/06 21:45:53 Attempting to use config file: /etc/chmgt/config
2018/01/06 21:45:53 Config file not found.
2018/01/06 21:45:53 No config files found. Exiting.
exit status 1
```

**Comment by mattjw79** [comment]
This might be a little cleaner: 77b8d6c706e6a72e194f129bc0c7b45bfb731927
