### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by lucasreed** [heimdal-rw/chmgt#50]
Opening this to start the discussion on Continuous Integration testing and what platform we should use. Travis is free to all opensource projects and it used by quite a lot of repos, so that's my first suggestion. With that being said, though I have no experience with any of them so I'm open to other options as well. Let me know what you think @mattjw79

**Comment by lucasreed** [comment]
Also, here is a post going over how you can locally run travis ci tests before committing: https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally

**Comment by mattjw79** [comment]
#52 adds Travis CI
